# Generated by Django 4.1.4 on 2023-05-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_remove_job_category_remove_job_employer_and_more'),
        ('employerprofile', '0002_alter_employer_company_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
