# Generated by Django 3.0.8 on 2020-09-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='dob',
        ),
    ]
