# Generated by Django 4.2 on 2023-05-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20200906_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidates',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
