# Generated by Django 4.2 on 2023-05-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_alter_candidates_id_alter_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidates',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
