# Generated by Django 4.1.4 on 2023-05-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
