# Generated by Django 4.1.4 on 2023-05-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_alter_job_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
