# Generated by Django 4.1.4 on 2023-05-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_alter_category_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='delay',
            field=models.CharField(blank=True, choices=[('1', '0.1'), ('2', '0.3'), ('3', '0.5'), ('4', '0.7')], max_length=2, null=True),
        ),
    ]
